name: Example

on: 
  pull_request:
    types: [opened, ready_for_review]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: | 
            '- [ ] please ensure that all necessary documentation has been updated on the
            documentation-data-ai repository. Once completed, please check the box and paste a link to the
            changes made in the documentation prior to the pull request being approved.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
