name: Example

on: 
  pull_request:
    types: [opened, ready_for_review]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: 'yoyo🤙🏻'
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
