name: Example

on: 
  pull_request:
    types: [opened, ready_for_review]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: '- [ ] has documentation been updated?'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  Incomplete_checklist:
    needs: example_comment_pr
    runs-on: ubuntu-latest
    name: Checklist checker
    steps:
      - name: Check Issue for Incomplete Checklist
        uses: mheap/require-checklist-action@v1
        with: 
          requireChecklist: true
